export default [
  "What about",
  "How about",
  "What do you think of",
  "Maybe some",
  "Would you like",
  "And how about some",
  "Would you do",
  "You feeling some",
  "May I interest you in some",
  "Could you get me some",
  "Pretty please, some",
  "Help me, I'm trapped inside",
  "How do you feel about",
  "Would you be down for",
  "Could you see us having",
  "Please, may I have some more",
  "Then can we try",
  "I've heard good things about",
  "Uhhhh...",
  "Then maybe some",
  "I could probably go for some",
  "Thinking maybe some"
]
