export default [
  "Chicken and Rice Casserole",
  "Burritos",
  "a new recipe from the D&D book",
  "White Wine Orzo",
  "Lemon Butter Chicken",
  "Ranch Breakfast",
  "Beef Stroganoff",
  "Teriyaki Chicken",
  "Candy Chicken",
  "Honey Sesame Chicken",
  "Chicken Stroganoff",
  "Minestrone Soup & Blueberry Muffins",
  "Baked Potato Soup",
  "Chicken Gnocchi Soup",
  "White Chicken Chili",
  "Frozen Pizza",
  "Stuffed Shells",
  "Taco Soup",
  "Chicken Rollups",
  "Enchilada Casserole",
  "Rustic Chicken"
]
